name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Remove unused directories
        # https://dev.to/mathio/squeezing-disk-space-from-github-actions-runners-an-engineers-guide-3pjg
        run: |
          df -h
          sudo rm -fr /usr/lib/jvm
          sudo rm -fr /usr/share/dotnet
          sudo rm -fr /usr/share/swift
          sudo rm -fr /usr/local/.ghcup
          sudo rm -fr /home/runner/.rustup
          sudo rm -fr /usr/local/julia*
          sudo rm -fr /usr/local/lib/android/sdk
          sudo rm -fr /usr/local/share/chromium
          sudo rm -fr /opt/hostedtoolcache/CodeQL
          sudo rm -fr /usr/local/share/powershell
          sudo rm -fr /opt/az
          sudo rm -fr /usr/lib/google-cloud-sdk
          df -h
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Setup Docker BuildKit
        uses: useblacksmith/setup-docker-builder@v1
      - name: Build & Push
        uses: docker/bake-action@v6
        with:
          source: .
          files: |
            versions.hcl
            recipe.hcl
          push: true
